concurrent = 1
check_interval = 0
connection_max_age = "15m0s"
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "test-runner"
  url = "http://gitlab:8929"
  id = 1
  token = "glrt-1zEP_2Xd7wGnaMcBDDmipm86MQpwOjEKdDozCnU6MQ8.01.170evpdmm"
  token_obtained_at = 2025-07-01T08:50:00Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "alpine"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/var/run/docker.sock:/var/run/docker.sock"]
    network_mode = "host"
    shm_size = 0
    network_mtu = 0

[[runners]]
  name = "test2"
  url = "http://gitlab:8929"
  id = 2
  token = "glrt-AKEZLjqSV-3XoE3xp5XSdW86MQpwOjEKdDozCnU6MQ8.01.171yv79ev"
  token_obtained_at = 2025-07-02T09:33:44Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "alpine"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    network_mtu = 0